language: node_js
node_js:
  - node
cache:
  directories:
    - ~/.cache
    - ~/.npm
install:
  - npm ci
script:
  - npm run lint
  - npm run start:ci &
  - npm run test:ci --record -key $CYPRESS_DASHBOARD_KEY CYPRESS_BASE_URL=http://localhost:8080
  - npm run build
  - kill $(jobs -p) || true

deploy:
  - provider: script
    script:
      - node ./gh.js
    on:
      - tags: true
      - branch: master
