# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ any ]
  pull_request:
    branches: [ master ]

jobs:

  cypress-run:

    name: E2E on Node v${{ matrix.node }}
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        node: [10.x, 12.x, 14.x]
        browser: [chrome, firefox]
    steps:

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: node -v

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci
